package forge.gui.cardcreator;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Line-preserving editor for the basic records owned by the structured creator. */
public final class CardScriptDocument {
    private final List<String> lines;
    private final boolean generatedOracle;

    private CardScriptDocument(final List<String> lines, final boolean generatedOracle) {
        this.lines = new ArrayList<>(lines);
        this.generatedOracle = generatedOracle;
    }

    public static CardScriptDocument fromText(final String text) {
        final String safeText = text == null ? "" : text.replace("\r\n", "\n").replace('\r', '\n');
        final List<String> lines = new ArrayList<>(List.of(safeText.split("\\n", -1)));
        if (!lines.isEmpty() && lines.get(lines.size() - 1).isEmpty()) lines.remove(lines.size() - 1);
        return new CardScriptDocument(lines, false);
    }

    public static CardScriptDocument fromDraft(final CardEditorDraft draft) {
        final List<String> lines = new ArrayList<>();
        lines.add("Name:" + nullToEmpty(draft.getName()));
        lines.add("ManaCost:" + nullToEmpty(draft.getManaCost()));
        lines.add("Types:" + nullToEmpty(draft.getTypes()));
        if (isInteger(draft.getPower()) && isInteger(draft.getToughness())) {
            lines.add("PT:" + draft.getPower() + "/" + draft.getToughness());
        }
        for (final String keyword : draft.getKeywords()) lines.add("K:" + keyword);
        lines.add("Oracle:" + String.join(", ", draft.getKeywords()));
        return new CardScriptDocument(lines, true);
    }

    /** Applies only the fields owned by the structured form and preserves all other records. */
    public void apply(final CardEditorDraft draft) {
        replaceFirstOrAdd("Name", "Name:" + nullToEmpty(draft.getName()), 0);
        replaceFirstOrAdd("ManaCost", "ManaCost:" + nullToEmpty(draft.getManaCost()), 1);
        replaceFirstOrAdd("Types", "Types:" + nullToEmpty(draft.getTypes()), 2);
        removeLine("PT");
        if (isInteger(draft.getPower()) && isInteger(draft.getToughness())) {
            int insertAt = indexOfPrefix("Types:");
            if (insertAt < 0) insertAt = Math.min(2, lines.size() - 1);
            lines.add(Math.min(lines.size(), insertAt + 1), "PT:" + draft.getPower() + "/" + draft.getToughness());
        }

        final List<String> unmanaged = new ArrayList<>();
        for (final String line : lines) {
            if (line.regionMatches(true, 0, "K:", 0, 2)) {
                final String keyword = line.substring(2).trim();
                if (CardCreatorKeywords.isManaged(keyword)) continue;
            }
            unmanaged.add(line);
        }
        lines.clear();
        lines.addAll(unmanaged);
        int insertAt = indexOfPrefix("PT:");
        if (insertAt < 0) insertAt = indexOfPrefix("Types:");
        insertAt = Math.min(lines.size(), insertAt + 1);
        int offset = 0;
        for (final String keyword : draft.getKeywords()) lines.add(insertAt + offset++, "K:" + keyword);
        if (generatedOracle) {
            // TODO: Once arbitrary abilities are editable, only replace Oracle text generated by
            // this form; preserving user-authored Oracle text is required for richer cards.
            final String oracle = "Oracle:" + String.join(", ", draft.getKeywords());
            final int oracleIndex = indexOfPrefix("Oracle:");
            if (oracleIndex >= 0) lines.set(oracleIndex, oracle);
            else lines.add(oracle);
        }
    }

    public String getText() {
        return String.join("\n", lines) + (lines.isEmpty() ? "" : "\n");
    }

    private void replaceFirstOrAdd(final String key, final String value, final int preferredIndex) {
        final int index = indexOfPrefix(key + ":");
        if (index >= 0) lines.set(index, value);
        else lines.add(Math.min(preferredIndex, lines.size()), value);
    }

    private void removeLine(final String key) {
        lines.removeIf(line -> line.regionMatches(true, 0, key + ":", 0, key.length() + 1));
    }

    private int indexOfPrefix(final String prefix) {
        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).toLowerCase(Locale.ROOT).startsWith(prefix.toLowerCase(Locale.ROOT))) return i;
        }
        return -1;
    }

    private static String nullToEmpty(final String value) { return value == null ? "" : value.trim(); }
    private static boolean isInteger(final String value) { return value != null && value.trim().matches("-?\\d+"); }
}
